### ISSUE TITLE
Occasional timeout Error in log since javascript 7.2.0

### ISSUE THREAD

**Issue by GitHoubi** [ioBroker/ioBroker.javascript#1458]
**Describe the bug**  
Since version 7.2. of the javascript Adapater I have timeout errors in two of my Blocky scripts. As far as I can see, everything regarding the scripts themselves works perfectly. The only thing is that these timeout errors keep appearing in the log.

This behavior is identical for versions 7.2.0, 7.3.0 and 7.4.0. If I go back to 7.1.6, the timeout errors also disappear, this can be reproduced as often as required.

**To Reproduce**  
Force SendTo action 

**Expected behavior**  
No Timeout Errors in the Log as with 7.1.6 or older

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.javascript/assets/99397913/5fcb4cfe-774e-4dfd-abe3-9c0ed7687ed0)

**Versions:**  
 - Adapter version: 7.2.0, 7.3.0, 7.4.0
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: Debian Bookworm

**Comment by klein0r** [comment]
Already fixed in b9f58609939b072b96a30af1538c06317364e618

Thanks for testing this beta version

**Comment by GitHoubi** [comment]
> Already fixed in [b9f5860](https://github.com/ioBroker/ioBroker.javascript/commit/b9f58609939b072b96a30af1538c06317364e618)
> 
> Thanks for testing this beta version

Hi Matthias

Klappt wunderbar mit dem neuen sandbox.js file, hab vielen herzlichen Dank.

**Comment by GitHoubi** [comment]
fixed with https://github.com/ioBroker/ioBroker.javascript/commit/b9f58609939b072b96a30af1538c06317364e618

**Comment by passuff** [comment]
I'm still facing this error with javascript 8.03. 
It seems to be connected to "send to" function block.

**Comment by klein0r** [comment]
> It seems to be connected to "send to" function block.

Yes, it can happen if you provide a callback function but you use sendTo to "all instances". In that case no instance returns a result and the sandbox returns a timeout (to ensure the async methods will not block forever).

@passuff Please share some code / examples which generates that issue.

**Comment by Apollon77** [comment]
When I remember correctly in this case the first answer should be used as result and being returned .... at least on js.controller level

**Comment by zaphod2** [comment]
![Screenshot 2024-05-01 094437](https://github.com/ioBroker/ioBroker.javascript/assets/96678159/9090f7e1-c3f4-420d-8a93-4c4afab025af)

![Screenshot 2024-05-01 094619](https://github.com/ioBroker/ioBroker.javascript/assets/96678159/e0262a1b-ead7-463b-a75e-09caa9d51038)

Abgesehen davon versteh ich den Timeout eh nicht, kann ich einstellen was ich will und gefühlt macht er was er will.

**Comment by klein0r** [comment]
@zaphod2 Welche version ist das? Bitte mit der aktuellsten beta testen.

**Comment by zaphod2** [comment]
Sorry, war v8.0.3
Habe jetzt mal v8.1.1 installiert.

**Comment by zaphod2** [comment]
Ist auch mit 8.1.1 vorhanden.

**Comment by zaphod2** [comment]
Ist auch mit 8.2.0 vorhanden.

**Comment by klein0r** [comment]
@zaphod2 Und wir auch in der nächsten Version enthalten sein, wenn sich hier am Issue nichts ändert...

**Comment by zaphod2** [comment]
mit 8.4.2 auch noch nicht behoben.

**Comment by klein0r** [comment]
@VierlingMt Hier geht es nicht um http-Blöcke, der Timeout der sendTo-Blöcke ist nicht konfigurierbar
